# Generated by Django 3.1.2 on 2020-12-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'funder'), (2, 'owner'), (3, 'auth')], null=True),
        ),
    ]
