# Generated by Django 3.1.2 on 2020-12-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201202_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='GEEtif',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
