# Generated by Django 3.1.2 on 2020-12-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201203_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forest',
            old_name='alt1',
            new_name='long1',
        ),
        migrations.RemoveField(
            model_name='forest',
            name='GEEtif',
        ),
        migrations.AddField(
            model_name='forest',
            name='gee_image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forest',
            name='gee_loss',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
