# Generated by Django 3.1.2 on 2020-12-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201216_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
