# Generated by Django 3.1.2 on 2020-12-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201231_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='gee_image',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='forest',
            name='gee_loss',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
