# Generated by Django 3.1.2 on 2021-01-20 03:29

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201231_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='gee_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='forest',
            name='gee_loss',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('attr1', models.IntegerField()),
                ('attr2', models.IntegerField()),
                ('attr3', models.IntegerField()),
                ('attr4', models.IntegerField()),
                ('area', jsonfield.fields.JSONField()),
                ('block_size', models.FloatField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='app.forest')),
            ],
        ),
    ]
